### ISSUE TITLE
Miscellaneous Issues with website

### ISSUE THREAD

**Issue by rossgalloway** [yam-finance/synths-www#160]
When the figma file is referenced in the comments below, please refer to this document: https://www.figma.com/file/VrNPpEvA2PnyrV1LDYdGQO/Yam-Synths?node-id=0%3A1

### All Pages:
- The notification sidebar that pops up covers over the top context bar, hiding the wallet address and pull down menu to interact with your wallet. This notifications sidebar should pop out below the top context bar so that the information in the top bar is not obscured. 

![image](https://user-images.githubusercontent.com/58150151/145103613-53ad8868-39bf-4279-a3b3-d6e1f9fcbec4.png)

- Switching between mainnet and polygon in the wallets drop down doesn't do anything. I still have to physically change this in metamask.
- The different pages should be called "explore", "synths", and "portfolio" for now.

### Explore Page
- on smaller screen widths, the top information boxes remain very wide and drop 1 box into a lower level even though there is plenty of room for them to shrink. They should be able to fit in the same space as all the information in the boxes below. Another option, would be to just move these information boxes into the space on the right, which has no use on this page.

![image](https://user-images.githubusercontent.com/58150151/145104156-3137f17e-2726-475b-944f-f6bae138c509.png)

- Eventually there is a point where the dynamic resizing seems to break and is in between mobile and desktop modes with a blank space on the left, none on the right, and the wallet info on the bottom.

![image](https://user-images.githubusercontent.com/58150151/145104675-a61b328a-9fed-4082-8f03-ff6b63f9b32e.png)

- Once small enough that we move into mobile mode, there are missing lines around the YAM Synths logo. Also note that in the figma file, the logo and block number are only shown when the hamburger menu is opened, which fills the whole screen. Also, we are showing TVL stats in this mode and there is room for the other stats as well next to it. Why are they not also included. This question and the hamburger functionality should be clarified with @blokku-chan 

![image](https://user-images.githubusercontent.com/58150151/145105778-2fb47212-b0d9-42d4-8949-399760d3dbf5.png)

- When running the mouse over the different synths, lines above and below the mouse-over disappear and re-appear awkwardly and inconsistently.
- Mouseover makes the whole row feel like a button, but only works as a button when clicking on the name or the arrow. Make the whole row the button.

### Synth (Markets) Pages

- Dynamic width scaling for this page and all synths is broken. The right panel does not move with the screen size but is cropped.
![image](https://user-images.githubusercontent.com/58150151/145106763-379e7701-9839-49b4-a317-690895f68cdf.png)
![image](https://user-images.githubusercontent.com/58150151/145106847-67b20c71-d369-4994-9321-838c4f50e653.png)

- At this size we have now lost the right section and 2 of the charts that were on the full page have disappeared. So we can't see over half our charts or mint synths.
![image](https://user-images.githubusercontent.com/58150151/145107320-55674761-a0d9-4a9d-b79d-03d9f70b7c9a.png)

- at some point we need to make the left column collapse into an expandable menu on mouse-over. it is using up far too much screen real estate for information that isn't relevant to the task at hand (minting or managing synths).
![image](https://user-images.githubusercontent.com/58150151/145107743-819dba62-d307-4863-b22b-254bf8fd5f54.png)

- clicking on "mint," "redeem," or "settle" from mobile mode causes the site to break and all content to disappear. It is still there, because when you make the screen wider again it comes back, so it must be moving stuff outside the frame.
![image](https://user-images.githubusercontent.com/58150151/145108293-399829be-9b6e-411d-ac02-d4ccaa4b3825.png)

- The "Go Long" and "Go Short" buttons end up with big gaps between them in many different screen sizes. In the figma file they are always shown next to each other and left justified.
![image](https://user-images.githubusercontent.com/58150151/145109088-61abca21-b8d5-4dfb-99b7-ba60a1f6da3b.png)

- Text justification in the "mint", "redeem", and "settle" menus is inconsistent. And it may just be my eyes, but the text sizes for different elements across pages seem to vary a lot.
- Misalignment of the right column and the line at the top bar.
![image](https://user-images.githubusercontent.com/58150151/145115693-4ec61d34-bace-4791-a973-cb7479816b32.png)
 
-  When navigating from the explore page to a synth page and then clicking on "mint" or "redeem" or "manage" sometimes all the info in the page disappears, similar to what happens when the screen is sized for mobile. navigating to a new synth or page brings it back.
![image](https://user-images.githubusercontent.com/58150151/145116165-4c6fdc55-6ca7-4769-86a9-b975e9e39a59.png)

- Once you click on one of the action buttons like "mint" there is no way to close that right column menu and it stays active even when you switch between synths.
- One of the charts should be all short tokens and the button should say "go short" and be red instead of both saying "go long and being green."

### Portolio Page

- See all issues under the Explore page as they are pretty much the same.

**Comment by ethedev** [comment]
this will be split into multiple issues, for next time please have it directly like so @rossgalloway
