### ISSUE TITLE
Fix notification sidebar

### ISSUE THREAD

**Issue by ethedev** [yam-finance/synths-www#163]
The notification sidebar that pops up covers over the top context bar, hiding the wallet address and pull down menu to interact with your wallet. This notifications sidebar should pop out below the top context bar so that the information in the top bar is not obscured.

![image](https://user-images.githubusercontent.com/58150151/145103613-53ad8868-39bf-4279-a3b3-d6e1f9fcbec4.png)

- Switching between mainnet and polygon in the wallets drop down doesn't do anything. I still have to physically change this in metamask.
- The different pages should be called "explore", "synths", and "portfolio" for now.

**Comment by wangtiger317** [comment]
fixed this
