### ISSUE TITLE
Fix explore page cards

### ISSUE THREAD

**Issue by ethedev** [yam-finance/synths-www#164]
On smaller screen widths, the top information boxes remain very wide and drop 1 box into a lower level even though there is plenty of room for them to shrink. They should be able to fit in the same space as all the information in the boxes below. Another option, would be to just move these information boxes into the space on the right, which has no use on this page.

- fix page cards to be on the same row instead of what is shown on the screenshot, keeping it as much compact as possible

![image](https://user-images.githubusercontent.com/58150151/145104156-3137f17e-2726-475b-944f-f6bae138c509.png)

**Comment by wangtiger317** [comment]
fixed this issues
