### ISSUE TITLE
Fix page items on resizing

### ISSUE THREAD

**Issue by ethedev** [yam-finance/synths-www#168]
At this size we have now lost the right section and 2 of the charts that were on the full page have disappeared. So we can't see over half our charts or mint synths.

1. fix missing items on page resizing
2. fix on the sidebar once you click on one of the action buttons like "mint" there is no way to close the mint/settle... sidebar and it stays active even when you switch between synths
3. fix on one of the charts it should be all short tokens and the button should say "go short" and be red instead of both saying "go long and being green" that is just a temporary updated as later this will be handled by @ElmoArmy on the sdk and functionality integration
4. fix the buttons, it should be wider or centered @blokku-chan some ideas on design might be well worth it

![image](https://user-images.githubusercontent.com/58150151/145109088-61abca21-b8d5-4dfb-99b7-ba60a1f6da3b.png)
![image](https://user-images.githubusercontent.com/58150151/145107320-55674761-a0d9-4a9d-b79d-03d9f70b7c9a.png)

- The "Go Long" and "Go Short" buttons end up with big gaps between them in many different screen sizes. In the figma file they are always shown next to each other and left justified.

**Comment by wangtiger317** [comment]
fixed 1 and 3 in this issues

**Comment by wangtiger317** [comment]
fixed 2 issue and pushed
